记录时间：2017-12-27 13:51:47,508 
线程ID:[5] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 120
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 61
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() 


记录时间：2017-12-27 13:51:47,508 
线程ID:[7] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 120
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 61
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 13:52:50,750 
线程ID:[5] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 120
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 31
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 13:53:09,970 
线程ID:[6] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.FormatException: 输入的不是有效的 Base-64 字符串，因为它包含非 Base-64 字符、两个以上的填充字符，或者填充字符间包含非法字符。
   在 System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   在 System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   在 System.Convert.FromBase64String(String s)
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 35
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 13:54:09,432 
线程ID:[6] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.FormatException: 输入的不是有效的 Base-64 字符串，因为它包含非 Base-64 字符、两个以上的填充字符，或者填充字符间包含非法字符。
   在 System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   在 System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   在 System.Convert.FromBase64String(String s)
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 35
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 13:58:10,332 
线程ID:[9] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 121
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 62
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() 


记录时间：2017-12-27 13:58:10,335 
线程ID:[7] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 121
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 62
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() 


记录时间：2017-12-27 13:58:10,369 
线程ID:[7] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 121
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 62
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() 


记录时间：2017-12-27 14:36:56,749 
线程ID:[12] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 124
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 65
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() 


记录时间：2017-12-27 14:36:56,751 
线程ID:[9] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 124
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 65
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() 


记录时间：2017-12-27 14:36:56,751 
线程ID:[13] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 124
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 65
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() 


记录时间：2017-12-27 14:36:56,776 
线程ID:[12] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 124
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 65
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() 


记录时间：2017-12-27 14:37:29,751 
线程ID:[5] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.FormatException: 未能找到任何可识别的数字。
   在 System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   在 System.Convert.ToByte(String value, Int32 fromBase)
   在 ZCSAPI.Common.DEncrypt.HashEncode.<>c__DisplayClass10_0.<GetBytesFromHexString>b__1(Int32 x) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 128
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   在 ZCSAPI.Common.DEncrypt.HashEncode.GetBytesFromHexString(String hexStr) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 126
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 --- 


记录时间：2017-12-27 14:40:14,162 
线程ID:[6] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.FormatException: 未能找到任何可识别的数字。
   在 System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   在 System.Convert.ToByte(String value, Int32 fromBase)
   在 ZCSAPI.Common.DEncrypt.HashEncode.<>c__DisplayClass10_0.<GetBytesFromHexString>b__1(Int32 x) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 128
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   在 ZCSAPI.Common.DEncrypt.HashEncode.GetBytesFromHexString(String hexStr) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 126
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 14:42:09,079 
线程ID:[9] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.FormatException: 未能找到任何可识别的数字。
   在 System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   在 System.Convert.ToByte(String value, Int32 fromBase)
   在 ZCSAPI.Common.DEncrypt.HashEncode.<>c__DisplayClass10_0.<GetBytesFromHexString>b__1(Int32 x) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 128
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   在 ZCSAPI.Common.DEncrypt.HashEncode.GetBytesFromHexString(String hexStr) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 126
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 14:47:34,349 
线程ID:[6] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.FormatException: 未能找到任何可识别的数字。
   在 System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   在 System.Convert.ToByte(String value, Int32 fromBase)
   在 ZCSAPI.Common.DEncrypt.HashEncode.<>c__DisplayClass10_0.<GetBytesFromHexString>b__1(Int32 x) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 128
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   在 ZCSAPI.Common.DEncrypt.HashEncode.GetBytesFromHexString(String hexStr) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 126
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 14:48:54,669 
线程ID:[9] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.FormatException: 未能找到任何可识别的数字。
   在 System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   在 System.Convert.ToByte(String value, Int32 fromBase)
   在 ZCSAPI.Common.DEncrypt.HashEncode.<>c__DisplayClass10_0.<GetBytesFromHexString>b__1(Int32 x) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 128
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   在 ZCSAPI.Common.DEncrypt.HashEncode.GetBytesFromHexString(String hexStr) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 126
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 14:49:32,058 
线程ID:[9] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.FormatException: 未能找到任何可识别的数字。
   在 System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   在 System.Convert.ToByte(String value, Int32 fromBase)
   在 ZCSAPI.Common.DEncrypt.HashEncode.<>c__DisplayClass10_0.<GetBytesFromHexString>b__1(Int32 x) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 128
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   在 ZCSAPI.Common.DEncrypt.HashEncode.GetBytesFromHexString(String hexStr) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 126
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 --- 


记录时间：2017-12-27 14:50:09,016 
线程ID:[9] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.FormatException: 未能找到任何可识别的数字。
   在 System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   在 System.Convert.ToByte(String value, Int32 fromBase)
   在 ZCSAPI.Common.DEncrypt.HashEncode.<>c__DisplayClass10_0.<GetBytesFromHexString>b__1(Int32 x) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 128
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   在 ZCSAPI.Common.DEncrypt.HashEncode.GetBytesFromHexString(String hexStr) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 126
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 14:52:08,691 
线程ID:[12] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.ArgumentException: Salt 不是最少为 8 个字节。
   在 System.Security.Cryptography.Rfc2898DeriveBytes.set_Salt(Byte[] value)
   在 System.Security.Cryptography.Rfc2898DeriveBytes..ctor(Byte[] password, Byte[] salt, Int32 iterations)
   在 System.Security.Cryptography.Rfc2898DeriveBytes..ctor(String password, Byte[] salt)
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 14:53:10,214 
线程ID:[6] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.ArgumentException: Salt 不是最少为 8 个字节。
   在 System.Security.Cryptography.Rfc2898DeriveBytes.set_Salt(Byte[] value)
   在 System.Security.Cryptography.Rfc2898DeriveBytes..ctor(Byte[] password, Byte[] salt, Int32 iterations)
   在 System.Security.Cryptography.Rfc2898DeriveBytes..ctor(String password, Byte[] salt)
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 --- 


记录时间：2017-12-27 14:56:26,767 
线程ID:[6] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.ArgumentException: Salt 不是最少为 8 个字节。
   在 System.Security.Cryptography.Rfc2898DeriveBytes.set_Salt(Byte[] value)
   在 System.Security.Cryptography.Rfc2898DeriveBytes..ctor(Byte[] password, Byte[] salt, Int32 iterations)
   在 System.Security.Cryptography.Rfc2898DeriveBytes..ctor(String password, Byte[] salt)
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 15:00:09,546 
线程ID:[7] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.ArgumentException: Salt 不是最少为 8 个字节。
   在 System.Security.Cryptography.Rfc2898DeriveBytes.set_Salt(Byte[] value)
   在 System.Security.Cryptography.Rfc2898DeriveBytes..ctor(Byte[] password, Byte[] salt, Int32 iterations)
   在 System.Security.Cryptography.Rfc2898DeriveBytes..ctor(String password, Byte[] salt)
   在 ZCSAPI.Common.DEncrypt.HashEncode.PBKDF2(String toBeEncrypted, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\HashEncode.cs:行号 80
   在 ZCSAPI.Common.DEncrypt.DEncrypt.CalculatePassword(String rawPassword, String salt) 位置 E:\zcsgit\ZCSAPI\ZCSAPI.Common\DEncrypt\DEncrypt.cs:行号 187
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 105
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


记录时间：2017-12-27 15:13:28,130 
线程ID:[14] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 124
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.LoginNameLogin(HttpActionContext actionContext, String userInfo) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 115
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 57
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


